project:
  type: fumadocs
  output-dir: ../.docs/
  render:
    - "index.md"
    - "docs/simulation/writing.qmd"
    - "**/*.qmd"
    - "**/*.ipynb"
    - "**/*.md"

format:
  fumadocs-md:
    extensions: [mdx]

